Add Architecture Name Prefix
AOSC-Dev/Buildbots pull request #8
Opened 2024-12-10 06:00 UTC by Shyliuli

我建议在PR中提供带有架构名前缀的主机名，以便进一步方便开发者的使用。

由于内容较多，此PR是基于 [AOSC Wiki](https://wiki.aosc.io/developer/infrastructure/buildbots/) 中提供的端口与架构对应模式，使用脚本进行了实现。相关脚本的详细内容可在 [剪贴板](https://aosc.io/paste/detail?id=841d4d1f-b583-4ec8-b50e-569a29c046fe) 中找到。

请注意，脚本尚未经过人工审查。如果您发现任何错误或可以改进的地方，欢迎随时提出指正。感谢您的支持与合作！

2024-12-10 06:08 UTC, Shyliuli commented
[trans.txt](https://github.com/user-attachments/files/18072807/trans.txt)
py脚本（由于gh限制无法上传py文件，故为txt）
py script (why txt:due to gh restrictions, py files cannot be uploaded...)

2024-12-11 11:07 UTC, KexyBiscuit requested changes
脚本可以放置到仓库内以便日后参考，比如 contrib/trans.py

另，依据 [PEP 394](https://peps.python.org/pep-0394/)，shebang 应引用 python3 或 python2 而非 python

2024-12-11 11:07 UTC, KexyBiscuit commented on ssh_config
> +Host Hydaelyn hydaelyn x86-Hydaelyn x86-hydaelyn
这里使用安同 OS 的正式架构名比较好，可以参考 <https://github.com/AOSC-Dev/autobuild4/blob/master/sets/arch_targets.json>

2024-12-11 11:07 UTC, KexyBiscuit commented on ssh_config
> +
麻烦手动移除多余的空行，保持一定程度上的美观

2024-12-11 11:07 UTC, KexyBiscuit commented on ssh_config
>  Host Misaka23333-direct misaka23333-direct
这部分也麻烦手动编辑一下，参考上面 relay 的主机名和架构前缀情况

2024-12-11 11:07 UTC, KexyBiscuit commented on ssh_config
> +
同上，若干处多余的空行

2024-12-11 12:20 UTC, KexyBiscuit commented on ssh_config
> +  # relay-cn
误触？

2024-12-11 12:20 UTC, KexyBiscuit commented on ssh_config
> +Host kp920-direct  arm64-kp920-direct
多了一个空格？

2024-12-11 12:22 UTC, Shyliuli commented on ssh_config
> +  # relay-cn
应该是...

2024-12-11 14:00 UTC, merged